baseURL = ""
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

[params]
# LoveIt 更改 | 0.2.0 LoveIt 主题版本
version = "0.2.X"
# 网站描述
description = "这是我的全新 Hugo 网站"
# 网站关键词
keywords = ["Theme", "Hugo"]
# 网站默认主题样式 ("light", "dark", "auto")
defaultTheme = "auto"
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = ""
# LoveIt 新增 | 0.1.1 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
# LoveIt 新增 | 0.2.0 日期格式
dateFormat = "2006-01-02"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/logo.png"]


[params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
title = "一曲广陵散"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10磁贴颜色
tileColor = "#da532c"

# 页面头部导航栏配置
[params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
[params.header.title]
    # LOGO 的 URL
    # 标题名称
    name = "一曲广陵散"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
    typeit = true

# 页面底部信息配置
  [params.footer]
    enable = true
    # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
    custom = ''
    # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
    hugo = true
    # LoveIt 新增 | 0.2.0 是否显示版权信息
    copyright = true
    # LoveIt 新增 | 0.2.0 是否显示作者
    author = true
    # 网站创立年份
    since = 2019
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = '<a rel="license external nofollow noopener noreffer" href="https://beian.miit.gov.cn/" target="_blank">苏ICP备2021001330号-1</a>'
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# LoveIt 新增 | 0.2.0 Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# LoveIt 新增 | 0.2.0 List (目录或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# 主页配置
[params.home]
# LoveIt 新增 | 0.2.0 RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
avatarURL = "/images/my.jpg"
# LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
title = ""
# 主页显示的网站副标题
subtitle = "柴米油盐酱醋茶，琴棋书画诗酒花！"
# 是否为副标题显示打字机动画
typeit = false
# 是否显示社交账号
social = true
# LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 20 
# LoveIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
# 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
defaultHiddenFromHomePage = false


 # 作者的社交信息设置
[params.social]
[params.social.GitHub]
# 排列图标时的权重 (权重越大, 图标的位置越靠后)
weight = 0
# 你的社交 ID
id = "kua-fu"
# 你的社交链接的前缀
prefix = "https://github.com/"
# 当鼠标停留在图标上时的提示内容
title = "GitHub"
[params.social.Stackoverflow]
# 排列图标时的权重 (权重越大, 图标的位置越靠后)
weight = 2
# 你的社交 ID
id = "6187624/thewind"
# 你的社交链接的前缀
prefix = "https://stackoverflow.com/users/"
# 当鼠标停留在图标上时的提示内容
title = "Stackoverflow"
[params.social.Zhihu]
# 排列图标时的权重 (权重越大, 图标的位置越靠后)
weight = 3
# 你的社交 ID
id = "yang-zhi-30-11"
# 你的社交链接的前缀
prefix = "https://www.zhihu.com/people/"
# 当鼠标停留在图标上时的提示内容
title = "知乎"

[params.social.Douban]
# 排列图标时的权重 (权重越大, 图标的位置越靠后)
weight = 4
# 你的社交 ID
id = "thewindyz"
# 你的社交链接的前缀
prefix = "https://www.douban.com/people/"
# 当鼠标停留在图标上时的提示内容
title = "豆瓣"

#itHub = "xxxx"
#Zhihu = ""
#Douban = ""
#Stackoverflow = ""
#Quora = ""
#Bilibili = ""
#Email = "xxxx@xxxx.com"
#RSS = true 

# 作者配置
[author]
name = "yz"
email = "1126978661@qq.com"
link = ""

[menu]
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1
[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 2
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 3

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false


# LoveIt 更改 | 0.2.0 评论系统设置
[params.page.comment]
enable = true
# Gitalk 评论系统设置
[params.page.comment.gitalk]
# LoveIt 新增 | 0.1.1
enable = true
owner = "yzthewind"
repo = "blog_gitalk"
clientId = "8e70465ecd960275a174"
clientSecret = "32c54e1095f64e2ac3dcfa4afed2e61d5444bc0d"
